name: app_base_flutter
description: "VAIS_Meeting_Room"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.0
  get: ^4.6.6
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  event_bus: ^2.0.1
  geolocator: ^13.0.1
  location: ^6.0.2
  flutter_html: ^3.0.0-beta.2
  injectable: ^2.5.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  bmprogresshud: ^1.0.3
  after_layout: ^1.2.0
  freezed_annotation: ^2.4.4
  flutter_localizations:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1

dev_dependencies:
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 600
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Bold.ttf
          weight: 600
